### ISSUE TITLE
Failure to build on 20.04

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/gpu_voxel_planning#9]
When building I currently get the error: 

```
In file included from /home/bradsaund/catkin_ws/src/planning/gpu_voxel_planning/include/gpu_voxel_planning/beliefs/beliefs.hpp:8,
                 from /home/bradsaund/catkin_ws/src/planning/gpu_voxel_planning/include/gpu_voxel_planning/state.hpp:9,
                 from /home/bradsaund/catkin_ws/src/planning/gpu_voxel_planning/include/gpu_voxel_planning/scenarios/scenarios.hpp:5,
                 from /home/bradsaund/catkin_ws/src/planning/gpu_voxel_planning/include/gpu_voxel_planning/scenarios/real_scenario.hpp:4,
                 from /home/bradsaund/catkin_ws/src/planning/gpu_voxel_planning/src/scenarios/real_scenario.cpp:1:
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected identifier before ‘!’ token
  105 |     static bool likely(const string_type& str)
      |                 ^~~~~~

```

One thread (https://github.com/xournalpp/xournalpp/issues/269) suggests this is due to the collision of boost's `likely` and the `likely` macro we have defined in `arc_utilities/arc_helpers.hpp`

**Comment by bsaund** [comment]
It builds now
